[package]
name = "vkey"
version = "0.1.0"
edition = "2021"

[dependencies]
freya = "0.3.0"
vi = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
