name: Build and Package VKey App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust via rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build (release) and create .app bundle
        run: |
          # cargo-bundle will build in release mode and create the .app inside target/release/bundle/osx
          cargo bundle --release --format osx

      - name: Zip the .app bundle (preserve macOS metadata)
        run: |
          APP_PATH=$(ls -d target/release/bundle/osx/*.app | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "Error: .app bundle not found in target/release/bundle/osx";
            exit 1;
          fi
          # Use ditto to properly zip macOS apps (keeps resource forks and Finder metadata)
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" VKey.app.zip
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VKey-app-bundle
          path: VKey.app.zip